services:
  app:
    user: root
    hostname: "${HOST_NAME:-project_environment}"
    image: e2eml_data
    container_name: e2eml-data-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: ${USER_NAME:-danhenriquex}
        USER_ID: ${USER_ID:-2000}
    # env_file:
    #   ~.envs/.app

    volumes:
      - ./:/app
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME}/.ssh
    ports:
      - 8888:8888

    ipc: host
    init: true
