services:
  app:
    user: root
    hostname: "${HOST_NAME:-project_environment}"
    image: project_environment
    container_name: project_environment-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: ${USER_NAME:-danilohssantana}
        USER_ID: ${USER_ID:-2000}
    # env_file:
    #   ~.envs/.app

    volumes:
      - ./:/app
      - ~/.config/gcloud:${HOME}/.config/gcloud
    ports:
      - 8080:8080

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    ipc: host
    init: true
